### ISSUE TITLE
'pyparsing<=1.5.7' distribution was not found error at start up of nidmviewer

### ISSUE THREAD

**Issue by cmaumet** [vsoch/nidmviewer#16]
This issue was reported through twitter by Jan-Bernard Marsman (‏@jbcmarsman): https://twitter.com/jbcmarsman/status/744879142148128768.
##### Traceback of the error on mac (MBP 2015, El Capitan):

```
$ nidmviewer
Traceback (most recent call last):
  File "/Users/marsman/anaconda/bin/nidmviewer", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Users/marsman/anaconda/lib/python2.7/site-packages/setuptools-19.2-py2.7.egg/pkg_resources/__init__.py", line 3138, in <module>
  File "/Users/marsman/anaconda/lib/python2.7/site-packages/setuptools-19.2-py2.7.egg/pkg_resources/__init__.py", line 3124, in _call_aside
  File "/Users/marsman/anaconda/lib/python2.7/site-packages/setuptools-19.2-py2.7.egg/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
  File "/Users/marsman/anaconda/lib/python2.7/site-packages/setuptools-19.2-py2.7.egg/pkg_resources/__init__.py", line 663, in _build_master
  File "/Users/marsman/anaconda/lib/python2.7/site-packages/setuptools-19.2-py2.7.egg/pkg_resources/__init__.py", line 676, in _build_from_requirements
  File "/Users/marsman/anaconda/lib/python2.7/site-packages/setuptools-19.2-py2.7.egg/pkg_resources/__init__.py", line 849, in resolve
pkg_resources.DistributionNotFound: The 'pyparsing<=1.5.7' distribution was not found and is required by rdfextras
```

More details in [NIDM notes](https://docs.google.com/document/d/1cAO_Lui_-6DmLxaA32-LI3tLSNlgQBnuKM-6s_E5JyQ/edit?usp=sharing).

**Comment by cmaumet** [comment]
Looks like this issue is related to the use of the `rdfextras` package. According to the [doc](https://rdfextras.readthedocs.io/en/latest/), `rdfextras` is "to be considered unstable in general". 

To make the install smoother, I think we could try and remove dependency on `rdfextras` and instead only use the core `rdflib` library. @vsoch: does that sound reasonable to you? Happy to have a look!
